export const SET_MOVIES_LIST = 'SET_MOVIES_LIST';
export const SET_ALL_COUNTRIES_LIST = 'SET_ALL_COUNTRIES_LIST';
export const SET_TOTAL_PAGE = 'SET_TOTAL_PAGE';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
